"""
seed_events.py
──────────────
Seeds the Supabase ``public.events`` table with realistic mock ASEAN event data.

Run (from inside backend-scrapper/):
    python seed_events.py              # insert all events
    python seed_events.py --dry-run    # preview without writing
    python seed_events.py --clear      # delete mock rows first, then re-seed

All mock phq_ids are prefixed with "mock-" so they are easy to identify and
can be removed without touching real PredictHQ data.
"""

from __future__ import annotations

import sys
import logging
import json
from datetime import datetime, timezone as tz
import click
from pathlib import Path

# ── Bootstrap path so config / db are importable ──────────────────────────────
sys.path.insert(0, str(Path(__file__).parent))

from config import settings  # noqa: E402  (import after sys.path patch)
from db import get_client    # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("seed_events")

# ── Unsplash image map (category → sized photo URL) ───────────────────────────
# Using specific curated photo IDs — no API key required for direct photo URLs.

_IMGS: dict[str, str] = {
    "concert":          "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=900&q=80",
    "festival":         "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=900&q=80",
    "lantern":          "https://images.unsplash.com/photo-1516916759473-600c07bc12d4?auto=format&fit=crop&w=900&q=80",
    "sports":           "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=900&q=80",
    "marathon":         "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=900&q=80",
    "football":         "https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=900&q=80",
    "expo":             "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=900&q=80",
    "conference":       "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=900&q=80",
    "cultural":         "https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=900&q=80",
    "traditional":      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=900&q=80",
    "food":             "https://images.unsplash.com/photo-1567529572289-09467b100db5?auto=format&fit=crop&w=900&q=80",
    "night_market":     "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=900&q=80",
    "fireworks":        "https://images.unsplash.com/photo-1499366440045-db76a22b79c8?auto=format&fit=crop&w=900&q=80",
    "art":              "https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=900&q=80",
    "dance":            "https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=900&q=80",
    "temple":           "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=80",
    "nature":           "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80",
    "market":           "https://images.unsplash.com/photo-1562516155-e0c1ee44059b?auto=format&fit=crop&w=900&q=80",
    "performing_arts":  "https://images.unsplash.com/photo-1549937436-c29a5e0a0440?auto=format&fit=crop&w=900&q=80",
    "tech":             "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80",
    "music":            "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=80",
    "beach":            "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80",
    "parade":           "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=900&q=80",
    "water":            "https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=900&q=80",
    "religious":        "https://images.unsplash.com/photo-1473177104440-ffee2f376098?auto=format&fit=crop&w=900&q=80",
    "gaming":           "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80",
    "fashion":          "https://images.unsplash.com/photo-1558618047-fd2e6e9c2f6c?auto=format&fit=crop&w=900&q=80",
    "film":             "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=900&q=80",
    "dragon_boat":      "https://images.unsplash.com/photo-1559559228-e8e6ecf2be1a?auto=format&fit=crop&w=900&q=80",
}


# ─── Helper ────────────────────────────────────────────────────────────────────

def _wkt(lng: float, lat: float) -> str:
    return f"POINT({lng} {lat})"


def _dt(s: str) -> str:
    """Return an ISO 8601 UTC string from 'YYYY-MM-DD[ HH:MM]'."""
    fmt = "%Y-%m-%d %H:%M" if " " in s else "%Y-%m-%d"
    return datetime.strptime(s, fmt).replace(tzinfo=tz.utc).isoformat()


# ─── Mock event definitions ────────────────────────────────────────────────────

MOCK_EVENTS: list[dict] = [

    # ── Indonesia ─────────────────────────────────────────────────────────────
    {
        "phq_id": "mock-id-001",
        "title": "Bali Arts Festival 2026",
        "description": "The annual Bali Arts Festival showcases traditional Balinese performing arts, dance, music, painting, and crafts from across the island. One of the most important cultural celebrations in Indonesia.",
        "category": "festivals",
        "labels": ["arts", "traditional", "culture", "performing-arts"],
        "start_dt": _dt("2026-06-13"),
        "end_dt":   _dt("2026-07-12"),
        "timezone": "Asia/Makassar",
        "coords":   _wkt(115.2191, -8.6705),
        "country": "ID", "country_name": "Indonesia",
        "state": "Bali", "city": "Denpasar",
        "venue_name": "Bali Arts Centre (Taman Werdhi Budaya)",
        "venue_address": "Jl. Nusa Indah, Denpasar, Bali 80235",
        "scope": "country", "rank": 82, "local_rank": 95,
        "phq_attendance": 200000, "predicted_spend": 4500000, "currency": "IDR",
        "image_url": _IMGS["traditional"],
        "entities": [{"name": "Taman Werdhi Budaya", "type": "venue"}],
    },
    {
        "phq_id": "mock-id-002",
        "title": "Jakarta International Java Jazz Festival 2026",
        "description": "Asia's largest jazz festival returns to Jakarta with world-class jazz, soul, R&B, fusion, and pop performances from hundreds of local and international artists across multiple stages.",
        "category": "concerts",
        "labels": ["jazz", "music", "international"],
        "start_dt": _dt("2026-03-06"),
        "end_dt":   _dt("2026-03-08"),
        "timezone": "Asia/Jakarta",
        "coords":   _wkt(106.9675, -6.1261),
        "country": "ID", "country_name": "Indonesia",
        "state": "DKI Jakarta", "city": "Jakarta",
        "venue_name": "Jakarta International Expo (JIExpo)",
        "venue_address": "Jl. H. Benyamin Sueb, Kemayoran, Jakarta 10620",
        "scope": "international", "rank": 88, "local_rank": 97,
        "phq_attendance": 120000, "predicted_spend": 9000000, "currency": "IDR",
        "image_url": _IMGS["concert"],
        "entities": [{"name": "JIExpo Kemayoran", "type": "venue"}],
    },
    {
        "phq_id": "mock-id-003",
        "title": "Borobudur Marathon 2026",
        "description": "A UNESCO heritage marathon set against the backdrop of the majestic Borobudur Temple. Runners circle a course with panoramic views of the world's largest Buddhist monument at sunrise.",
        "category": "sports",
        "labels": ["marathon", "running", "heritage"],
        "start_dt": _dt("2026-11-15 05:00"),
        "end_dt":   _dt("2026-11-15 14:00"),
        "timezone": "Asia/Jakarta",
        "coords":   _wkt(110.2038, -7.6079),
        "country": "ID", "country_name": "Indonesia",
        "state": "Central Java", "city": "Magelang",
        "venue_name": "Borobudur Temple Complex",
        "venue_address": "Jl. Badrawati, Borobudur, Magelang, Central Java",
        "scope": "international", "rank": 76, "local_rank": 90,
        "phq_attendance": 10000, "predicted_spend": 2000000, "currency": "IDR",
        "image_url": _IMGS["marathon"],
        "entities": [{"name": "Borobudur Temple", "type": "venue"}],
    },
    {
        "phq_id": "mock-id-004",
        "title": "Yogyakarta Gamelan & Wayang Festival",
        "description": "A week-long celebration of Javanese classical arts — gamelan orchestras, shadow puppet (wayang kulit) performances, and batik exhibitions in the royal city of Yogyakarta.",
        "category": "performing-arts",
        "labels": ["gamelan", "wayang", "batik", "traditional", "java"],
        "start_dt": _dt("2026-08-17"),
        "end_dt":   _dt("2026-08-23"),
        "timezone": "Asia/Jakarta",
        "coords":   _wkt(110.3647, -7.8014),
        "country": "ID", "country_name": "Indonesia",
        "state": "Special Region of Yogyakarta", "city": "Yogyakarta",
        "venue_name": "Kraton Ngayogyakarta Hadiningrat",
        "venue_address": "Jl. Rotowijayan Blok No.1, Yogyakarta",
        "scope": "region", "rank": 70, "local_rank": 92,
        "phq_attendance": 50000, "predicted_spend": 1200000, "currency": "IDR",
        "image_url": _IMGS["cultural"],
        "entities": [{"name": "Kraton Palace", "type": "venue"}],
    },
    {
        "phq_id": "mock-id-005",
        "title": "Indonesia International Motor Show 2026",
        "description": "IIMS is the largest automotive exhibition in Southeast Asia, featuring the latest car, motorcycle, and commercial vehicle launches alongside technology showcases from global brands.",
        "category": "expos",
        "labels": ["automotive", "technology", "exhibition"],
        "start_dt": _dt("2026-02-19"),
        "end_dt":   _dt("2026-03-01"),
        "timezone": "Asia/Jakarta",
        "coords":   _wkt(106.9675, -6.1261),
        "country": "ID", "country_name": "Indonesia",
        "state": "DKI Jakarta", "city": "Jakarta",
        "venue_name": "JIExpo Kemayoran",
        "venue_address": "Jl. H. Benyamin Sueb, Kemayoran, Jakarta",
        "scope": "international", "rank": 80, "local_rank": 94,
        "phq_attendance": 350000, "predicted_spend": 12000000, "currency": "IDR",
        "image_url": _IMGS["expo"],
        "entities": [{"name": "JIExpo Kemayoran", "type": "venue"}],
    },

    # ── Singapore ─────────────────────────────────────────────────────────────
    {
        "phq_id": "mock-sg-001",
        "title": "Singapore Grand Prix 2026",
        "description": "The Formula 1 Singapore Airlines Singapore Grand Prix lights up the Marina Bay Street Circuit. The world's only night race combines motorsport with a stunning cityscapeback drop.",
        "category": "sports",
        "labels": ["formula1", "motorsport", "night-race"],
        "start_dt": _dt("2026-09-18"),
        "end_dt":   _dt("2026-09-20"),
        "timezone": "Asia/Singapore",
        "coords":   _wkt(103.8631, 1.2914),
        "country": "SG", "country_name": "Singapore",
        "state": "Central Region", "city": "Singapore",
        "venue_name": "Marina Bay Street Circuit",
        "venue_address": "10 Paddock Way, Marina Bay, Singapore 018956",
        "scope": "international", "rank": 95, "local_rank": 98,
        "phq_attendance": 260000, "predicted_spend": 150000000, "currency": "SGD",
        "image_url": _IMGS["sports"],
        "entities": [{"name": "Marina Bay Street Circuit", "type": "venue"}],
    },
    {
        "phq_id": "mock-sg-002",
        "title": "Singapore Food Festival 2026",
        "description": "Singapore's premier gastronomic event celebrating the city-state's diverse hawker culture and culinary heritage, featuring celebrity chef dinners, cooking masterclasses, and food markets.",
        "category": "festivals",
        "labels": ["food", "culinary", "hawker", "culture"],
        "start_dt": _dt("2026-07-09"),
        "end_dt":   _dt("2026-07-19"),
        "timezone": "Asia/Singapore",
        "coords":   _wkt(103.8566, 1.2860),
        "country": "SG", "country_name": "Singapore",
        "state": "Central Area", "city": "Singapore",
        "venue_name": "Various locations across Marina Bay & Chinatown",
        "venue_address": "Marina Bay Sands, 10 Bayfront Ave, Singapore",
        "scope": "country", "rank": 79, "local_rank": 91,
        "phq_attendance": 80000, "predicted_spend": 5000000, "currency": "SGD",
        "image_url": _IMGS["food"],
        "entities": [{"name": "Marina Bay Sands", "type": "venue"}],
    },
    {
        "phq_id": "mock-sg-003",
        "title": "Singapore International Film Festival 2026",
        "description": "SGIFF is one of Asia's most prestigious film festivals, showcasing Southeast Asian cinema and independent films from around the world, with screenings, director Q&As, and awards.",
        "category": "festivals",
        "labels": ["film", "cinema", "arts", "international"],
        "start_dt": _dt("2026-11-26"),
        "end_dt":   _dt("2026-12-06"),
        "timezone": "Asia/Singapore",
        "coords":   _wkt(103.8565, 1.2995),
        "country": "SG", "country_name": "Singapore",
        "state": "Central Region", "city": "Singapore",
        "venue_name": "Shaw Theatres, The Projector, Cathay Cineplexes",
        "venue_address": "6 Raffles Blvd, Marina Square, Singapore 039594",
        "scope": "international", "rank": 74, "local_rank": 88,
        "phq_attendance": 30000, "predicted_spend": 3000000, "currency": "SGD",
        "image_url": _IMGS["film"],
        "entities": [],
    },
    {
        "phq_id": "mock-sg-004",
        "title": "Chingay Parade Singapore 2027",
        "description": "Asia's largest street parade celebrates Chinese New Year with a spectacular procession of floats, acrobats, stilt-walkers, lion dancers, and multi-cultural performances along Orchard Road.",
        "category": "community",
        "labels": ["parade", "chinese-new-year", "multicultural"],
        "start_dt": _dt("2027-02-06"),
        "end_dt":   _dt("2027-02-07"),
        "timezone": "Asia/Singapore",
        "coords":   _wkt(103.8314, 1.3036),
        "country": "SG", "country_name": "Singapore",
        "state": "Orchard", "city": "Singapore",
        "venue_name": "F1 Pit Building & Padang",
        "venue_address": "1 Republic Blvd, Singapore 038975",
        "scope": "international", "rank": 83, "local_rank": 96,
        "phq_attendance": 100000, "predicted_spend": 8000000, "currency": "SGD",
        "image_url": _IMGS["parade"],
        "entities": [],
    },

    # ── Malaysia ──────────────────────────────────────────────────────────────
    {
        "phq_id": "mock-my-001",
        "title": "Rainforest World Music Festival 2026",
        "description": "Set in the ancient rainforest of Sarawak Cultural Village atop Mount Santubong, this iconic festival brings together musicians from different tribal cultures worldwide for three days of music and workshops.",
        "category": "festivals",
        "labels": ["music", "rainforest", "world-music", "borneo", "tribal"],
        "start_dt": _dt("2026-07-10"),
        "end_dt":   _dt("2026-07-12"),
        "timezone": "Asia/Kuching",
        "coords":   _wkt(110.3592, 1.5726),
        "country": "MY", "country_name": "Malaysia",
        "state": "Sarawak", "city": "Kuching",
        "venue_name": "Sarawak Cultural Village",
        "venue_address": "Pantai Damai Santubong, 93756 Kuching, Sarawak",
        "scope": "international", "rank": 81, "local_rank": 96,
        "phq_attendance": 20000, "predicted_spend": 6000000, "currency": "MYR",
        "image_url": _IMGS["music"],
        "entities": [{"name": "Sarawak Cultural Village", "type": "venue"}],
    },
    {
        "phq_id": "mock-my-002",
        "title": "Thaipusam Penang 2027",
        "description": "One of Hinduism's most dramatic festivals, where devotees carry kavadi in thanksgiving to Lord Murugan. The Penang procession from Sri Mahamariamman Temple to Waterfall Hill Temple draws massive crowds.",
        "category": "observances",
        "labels": ["religious", "hindu", "thaipusam", "cultural"],
        "start_dt": _dt("2027-02-10"),
        "end_dt":   _dt("2027-02-11"),
        "timezone": "Asia/Kuala_Lumpur",
        "coords":   _wkt(100.3303, 5.4141),
        "country": "MY", "country_name": "Malaysia",
        "state": "Penang", "city": "George Town",
        "venue_name": "Sri Mahamariamman Temple Waterfall",
        "venue_address": "Jalan Kebun Bunga, Georgetown, Penang",
        "scope": "country", "rank": 77, "local_rank": 94,
        "phq_attendance": 800000, "predicted_spend": 15000000, "currency": "MYR",
        "image_url": _IMGS["religious"],
        "entities": [],
    },
    {
        "phq_id": "mock-my-003",
        "title": "Malaysia International Drone Show 2026",
        "description": "Hundreds of programmable drones illuminate the Kuala Lumpur night sky creating 3D aerial art installations and animations above the iconic Petronas Twin Towers.",
        "category": "community",
        "labels": ["drones", "technology", "light-show", "kl"],
        "start_dt": _dt("2026-08-31 20:00"),
        "end_dt":   _dt("2026-08-31 22:00"),
        "timezone": "Asia/Kuala_Lumpur",
        "coords":   _wkt(101.7119, 3.1579),
        "country": "MY", "country_name": "Malaysia",
        "state": "Federal Territory", "city": "Kuala Lumpur",
        "venue_name": "KLCC Park",
        "venue_address": "Jalan Ampang, Kuala Lumpur City Centre, 50088 KL",
        "scope": "country", "rank": 78, "local_rank": 92,
        "phq_attendance": 40000, "predicted_spend": 3500000, "currency": "MYR",
        "image_url": _IMGS["fireworks"],
        "entities": [{"name": "KLCC Park", "type": "venue"}],
    },
    {
        "phq_id": "mock-my-004",
        "title": "Borneo Cultural Festival 2026",
        "description": "Miri hosts this vibrant celebration of Bornean indigenous cultures featuring the Iban, Bidayuh, Melanau, and Orang Ulu communities with traditional music, dance, crafts, and rituals.",
        "category": "festivals",
        "labels": ["borneo", "indigenous", "iban", "bidayuh", "traditional"],
        "start_dt": _dt("2026-07-21"),
        "end_dt":   _dt("2026-07-27"),
        "timezone": "Asia/Kuching",
        "coords":   _wkt(113.9914, 4.3995),
        "country": "MY", "country_name": "Malaysia",
        "state": "Sarawak", "city": "Miri",
        "venue_name": "Miri City Fan",
        "venue_address": "Jalan Kipas, 98000 Miri, Sarawak",
        "scope": "region", "rank": 66, "local_rank": 90,
        "phq_attendance": 60000, "predicted_spend": 2500000, "currency": "MYR",
        "image_url": _IMGS["traditional"],
        "entities": [],
    },

    # ── Thailand ──────────────────────────────────────────────────────────────
    {
        "phq_id": "mock-th-001",
        "title": "Songkran Water Festival Chiang Mai 2026",
        "description": "Chiang Mai hosts the world's largest water fight for Thai New Year. The entire old city moat area transforms into five days of water battles, sand castles, and merit-making ceremonies.",
        "category": "festivals",
        "labels": ["songkran", "water", "thai-new-year", "cultural"],
        "start_dt": _dt("2026-04-13"),
        "end_dt":   _dt("2026-04-17"),
        "timezone": "Asia/Bangkok",
        "coords":   _wkt(98.9853, 18.7961),
        "country": "TH", "country_name": "Thailand",
        "state": "Chiang Mai", "city": "Chiang Mai",
        "venue_name": "Chiang Mai Old City Moat",
        "venue_address": "Old City (Mueang Kao), Chiang Mai 50200",
        "scope": "international", "rank": 90, "local_rank": 99,
        "phq_attendance": 500000, "predicted_spend": 20000000, "currency": "THB",
        "image_url": _IMGS["water"],
        "entities": [],
    },
    {
        "phq_id": "mock-th-002",
        "title": "Yi Peng Lantern Festival 2026",
        "description": "Thousands of paper sky lanterns released simultaneously light up the night sky above Chiang Mai in one of the world's most beautiful festivals, coinciding with Loy Krathong.",
        "category": "observances",
        "labels": ["lanterns", "yi-peng", "loy-krathong", "light", "buddhist"],
        "start_dt": _dt("2026-11-21 18:00"),
        "end_dt":   _dt("2026-11-22 00:00"),
        "timezone": "Asia/Bangkok",
        "coords":   _wkt(98.9667, 18.7962),
        "country": "TH", "country_name": "Thailand",
        "state": "Chiang Mai", "city": "Chiang Mai",
        "venue_name": "Mae Jo University",
        "venue_address": "63 Moo 4, Wang Hin, San Sai, Chiang Mai 50290",
        "scope": "international", "rank": 92, "local_rank": 98,
        "phq_attendance": 10000, "predicted_spend": 5000000, "currency": "THB",
        "image_url": _IMGS["lantern"],
        "entities": [],
    },
    {
        "phq_id": "mock-th-003",
        "title": "Bangkok International Film Festival 2026",
        "description": "BIFF returns to Bangkok's premier cinemas with curated screenings of new Asian and international films, special retrospectives, and industry events celebrating Southeast Asian cinema.",
        "category": "festivals",
        "labels": ["film", "cinema", "arts"],
        "start_dt": _dt("2026-09-24"),
        "end_dt":   _dt("2026-10-04"),
        "timezone": "Asia/Bangkok",
        "coords":   _wkt(100.5018, 13.7563),
        "country": "TH", "country_name": "Thailand",
        "state": "Bangkok", "city": "Bangkok",
        "venue_name": "CentralWorld & Siam Paragon Cineplex",
        "venue_address": "4, 4/1-4/2 Rajdamri Rd, Bangkok 10330",
        "scope": "international", "rank": 73, "local_rank": 87,
        "phq_attendance": 25000, "predicted_spend": 4000000, "currency": "THB",
        "image_url": _IMGS["film"],
        "entities": [],
    },
    {
        "phq_id": "mock-th-004",
        "title": "SEA Games 2027 — Bangkok",
        "description": "Thailand hosts the 35th Southeast Asian Games, the region's premier multi-sport event uniting 11 ASEAN nations in friendly competition across 40+ sports disciplines.",
        "category": "sports",
        "labels": ["sea-games", "multi-sport", "asean", "olympic"],
        "start_dt": _dt("2027-07-10"),
        "end_dt":   _dt("2027-07-21"),
        "timezone": "Asia/Bangkok",
        "coords":   _wkt(100.6041, 13.7296),
        "country": "TH", "country_name": "Thailand",
        "state": "Bangkok", "city": "Bangkok",
        "venue_name": "National Stadium & Rajamangala National Stadium",
        "venue_address": "Pathumwan, Bangkok 10330",
        "scope": "international", "rank": 96, "local_rank": 99,
        "phq_attendance": 700000, "predicted_spend": 80000000, "currency": "THB",
        "image_url": _IMGS["sports"],
        "entities": [],
    },

    # ── Vietnam ───────────────────────────────────────────────────────────────
    {
        "phq_id": "mock-vn-001",
        "title": "Hội An Lantern Festival 2026",
        "description": "On the 14th day of each lunar month, Hội An Ancient Town releases all electric lights and glows entirely by candle and lantern light. The November full-moon edition is the most spectacular.",
        "category": "observances",
        "labels": ["lanterns", "hoi-an", "heritage", "lunar"],
        "start_dt": _dt("2026-11-11 18:00"),
        "end_dt":   _dt("2026-11-11 23:00"),
        "timezone": "Asia/Ho_Chi_Minh",
        "coords":   _wkt(108.3274, 15.8801),
        "country": "VN", "country_name": "Vietnam",
        "state": "Quảng Nam", "city": "Hội An",
        "venue_name": "Hội An Ancient Town",
        "venue_address": "Hội An Ancient Town, Quảng Nam Province, Vietnam",
        "scope": "international", "rank": 84, "local_rank": 97,
        "phq_attendance": 15000, "predicted_spend": 3000000, "currency": "VND",
        "image_url": _IMGS["lantern"],
        "entities": [],
    },
    {
        "phq_id": "mock-vn-002",
        "title": "Ho Chi Minh City Marathon 2026",
        "description": "The HCMC International Marathon takes runners through the heart of the city past colonial landmarks. The 42 km full marathon, half marathon, and 10 km fun run categories attract thousands from across Asia.",
        "category": "sports",
        "labels": ["marathon", "running", "city-race"],
        "start_dt": _dt("2026-01-04 05:00"),
        "end_dt":   _dt("2026-01-04 14:00"),
        "timezone": "Asia/Ho_Chi_Minh",
        "coords":   _wkt(106.6297, 10.8231),
        "country": "VN", "country_name": "Vietnam",
        "state": "Ho Chi Minh City", "city": "Ho Chi Minh City",
        "venue_name": "Nguyễn Huệ Walking Street",
        "venue_address": "Nguyễn Huệ Blvd, District 1, HCMC",
        "scope": "international", "rank": 72, "local_rank": 89,
        "phq_attendance": 12000, "predicted_spend": 2000000, "currency": "VND",
        "image_url": _IMGS["marathon"],
        "entities": [],
    },
    {
        "phq_id": "mock-vn-003",
        "title": "Huế Festival 2026",
        "description": "Held biennially in the ancient royal capital, Huế Festival features royal court music, traditional theatre, boat races on the Perfume River, and craft exhibitions celebrating Vietnam's imperial heritage.",
        "category": "festivals",
        "labels": ["hue", "imperial", "heritage", "cultural", "royal"],
        "start_dt": _dt("2026-04-26"),
        "end_dt":   _dt("2026-05-02"),
        "timezone": "Asia/Ho_Chi_Minh",
        "coords":   _wkt(107.5909, 16.4637),
        "country": "VN", "country_name": "Vietnam",
        "state": "Thừa Thiên Huế", "city": "Huế",
        "venue_name": "Hue Imperial Citadel",
        "venue_address": "23 Tháng 8 St, Phú Hiệp, Huế, Vietnam",
        "scope": "country", "rank": 78, "local_rank": 95,
        "phq_attendance": 100000, "predicted_spend": 8000000, "currency": "VND",
        "image_url": _IMGS["cultural"],
        "entities": [],
    },

    # ── Philippines ───────────────────────────────────────────────────────────
    {
        "phq_id": "mock-ph-001",
        "title": "Sinulog Festival Cebu 2026",
        "description": "One of the Philippines' grandest fiestas, Sinulog celebrates the Feast of the Santo Niño with a grand parade of millions of devotees dancing the two-steps-forward one-step-back sinulog dance.",
        "category": "festivals",
        "labels": ["sinulog", "santo-nino", "cebu", "religious", "festival"],
        "start_dt": _dt("2026-01-18"),
        "end_dt":   _dt("2026-01-18"),
        "timezone": "Asia/Manila",
        "coords":   _wkt(123.8907, 10.3157),
        "country": "PH", "country_name": "Philippines",
        "state": "Cebu", "city": "Cebu City",
        "venue_name": "Cebu City Streets & Basilica Minore del Santo Niño",
        "venue_address": "Osmeña Blvd, Cebu City, 6000 Cebu",
        "scope": "international", "rank": 87, "local_rank": 98,
        "phq_attendance": 2000000, "predicted_spend": 10000000, "currency": "PHP",
        "image_url": _IMGS["parade"],
        "entities": [],
    },
    {
        "phq_id": "mock-ph-002",
        "title": "Manila International Book Fair 2026",
        "description": "The Philippines' biggest literary event brings together publishers, authors, illustrators, and booklovers for five days of book launches, author readings, and discounts at the SMX Convention Center.",
        "category": "expos",
        "labels": ["books", "literature", "publishing"],
        "start_dt": _dt("2026-09-16"),
        "end_dt":   _dt("2026-09-20"),
        "timezone": "Asia/Manila",
        "coords":   _wkt(121.0244, 14.5548),
        "country": "PH", "country_name": "Philippines",
        "state": "Metro Manila", "city": "Pasay",
        "venue_name": "SMX Convention Center Manila",
        "venue_address": "Mall of Asia Complex, Pasay City, Metro Manila",
        "scope": "country", "rank": 65, "local_rank": 85,
        "phq_attendance": 100000, "predicted_spend": 4000000, "currency": "PHP",
        "image_url": _IMGS["expo"],
        "entities": [],
    },
    {
        "phq_id": "mock-ph-003",
        "title": "Panagbenga Flower Festival Baguio 2026",
        "description": "Baguio City's month-long flower festival in February features spectacular float parades, street dancing, and flower-themed displays celebrating the city's highland blooms after a 1990 earthquake.",
        "category": "festivals",
        "labels": ["flowers", "parade", "baguio", "highland"],
        "start_dt": _dt("2026-02-01"),
        "end_dt":   _dt("2026-02-28"),
        "timezone": "Asia/Manila",
        "coords":   _wkt(120.5960, 16.4023),
        "country": "PH", "country_name": "Philippines",
        "state": "Benguet", "city": "Baguio City",
        "venue_name": "Baguio City Center",
        "venue_address": "Session Road, Baguio City, Benguet 2600",
        "scope": "country", "rank": 75, "local_rank": 93,
        "phq_attendance": 200000, "predicted_spend": 6000000, "currency": "PHP",
        "image_url": _IMGS["festival"],
        "entities": [],
    },

    # ── Cambodia ──────────────────────────────────────────────────────────────
    {
        "phq_id": "mock-kh-001",
        "title": "Phnom Penh Water Festival (Bon Om Touk) 2026",
        "description": "Cambodia's most popular festival marks the reversal of the Tonle Sap River. Dragon boat races on the Mekong draw hundreds of thousands, with fireworks and illuminated boat processions at night.",
        "category": "festivals",
        "labels": ["water-festival", "dragon-boat", "tonle-sap", "cambodia"],
        "start_dt": _dt("2026-11-07"),
        "end_dt":   _dt("2026-11-09"),
        "timezone": "Asia/Phnom_Penh",
        "coords":   _wkt(104.9272, 11.5564),
        "country": "KH", "country_name": "Cambodia",
        "state": "Phnom Penh", "city": "Phnom Penh",
        "venue_name": "Tonle Sap & Mekong Riverside",
        "venue_address": "Sisowath Quay, Phnom Penh, Cambodia",
        "scope": "country", "rank": 83, "local_rank": 97,
        "phq_attendance": 1500000, "predicted_spend": 8000000, "currency": "KHR",
        "image_url": _IMGS["dragon_boat"],
        "entities": [],
    },
    {
        "phq_id": "mock-kh-002",
        "title": "Angkor Sangkranta (Khmer New Year) 2026",
        "description": "Khmer New Year celebrated at the iconic Angkor Wat complex includes traditional games, music, and cultural ceremonies welcoming the new year amid the UNESCO world heritage site.",
        "category": "observances",
        "labels": ["khmer-new-year", "angkor", "heritage", "cultural"],
        "start_dt": _dt("2026-04-13"),
        "end_dt":   _dt("2026-04-16"),
        "timezone": "Asia/Phnom_Penh",
        "coords":   _wkt(103.8670, 13.4125),
        "country": "KH", "country_name": "Cambodia",
        "state": "Siem Reap", "city": "Siem Reap",
        "venue_name": "Angkor Wat Temple Complex",
        "venue_address": "Angkor Archeological Park, Siem Reap Province",
        "scope": "country", "rank": 80, "local_rank": 95,
        "phq_attendance": 50000, "predicted_spend": 5000000, "currency": "KHR",
        "image_url": _IMGS["temple"],
        "entities": [{"name": "Angkor Wat", "type": "venue"}],
    },

    # ── Myanmar ───────────────────────────────────────────────────────────────
    {
        "phq_id": "mock-mm-001",
        "title": "Thadingyut Festival of Lights Myanmar 2026",
        "description": "Marking the end of Buddhist Lent, Thadingyut is Myanmar's festival of lights. Streets, homes, and pagodas are illuminated with candles and electric bulbs for three days of celebration.",
        "category": "observances",
        "labels": ["thadingyut", "lights", "buddhist", "lent"],
        "start_dt": _dt("2026-10-09"),
        "end_dt":   _dt("2026-10-11"),
        "timezone": "Asia/Rangoon",
        "coords":   _wkt(96.1562, 16.8409),
        "country": "MM", "country_name": "Myanmar",
        "state": "Yangon Region", "city": "Yangon",
        "venue_name": "Shwedagon Pagoda & City Streets",
        "venue_address": "Shwedagon Pagoda Rd, Yangon, Myanmar",
        "scope": "country", "rank": 70, "local_rank": 93,
        "phq_attendance": 500000, "predicted_spend": 3000000, "currency": "MMK",
        "image_url": _IMGS["religious"],
        "entities": [{"name": "Shwedagon Pagoda", "type": "venue"}],
    },

    # ── Laos ──────────────────────────────────────────────────────────────────
    {
        "phq_id": "mock-la-001",
        "title": "Luang Prabang Film Festival 2026",
        "description": "Southeast Asia's most intimate film festival screens critically acclaimed Asian cinema in the UNESCO-listed heritage city of Luang Prabang. Free outdoor screenings and director talks.",
        "category": "festivals",
        "labels": ["film", "cinema", "heritage", "luang-prabang"],
        "start_dt": _dt("2026-12-05"),
        "end_dt":   _dt("2026-12-09"),
        "timezone": "Asia/Vientiane",
        "coords":   _wkt(102.1307, 19.8856),
        "country": "LA", "country_name": "Laos",
        "state": "Luang Prabang", "city": "Luang Prabang",
        "venue_name": "Heritage House Luang Prabang",
        "venue_address": "Luang Prabang, Luang Prabang Province, Laos",
        "scope": "international", "rank": 64, "local_rank": 88,
        "phq_attendance": 5000, "predicted_spend": 1000000, "currency": "LAK",
        "image_url": _IMGS["film"],
        "entities": [],
    },
    {
        "phq_id": "mock-la-002",
        "title": "Boun Bang Fai (Rocket Festival) Vientiane 2026",
        "description": "Ancient Lao tradition where hand-crafted bamboo rockets are fired into the sky to encourage rain for the rice-planting season, accompanied by music, dancing, and processions.",
        "category": "festivals",
        "labels": ["rocket-festival", "rain", "boun-bang-fai", "traditional"],
        "start_dt": _dt("2026-05-16"),
        "end_dt":   _dt("2026-05-17"),
        "timezone": "Asia/Vientiane",
        "coords":   _wkt(102.6331, 17.9757),
        "country": "LA", "country_name": "Laos",
        "state": "Vientiane Prefecture", "city": "Vientiane",
        "venue_name": "That Luang Stupa Grounds",
        "venue_address": "That Luang Rd, Vientiane, Laos",
        "scope": "country", "rank": 66, "local_rank": 90,
        "phq_attendance": 30000, "predicted_spend": 800000, "currency": "LAK",
        "image_url": _IMGS["fireworks"],
        "entities": [],
    },

    # ── Brunei ────────────────────────────────────────────────────────────────
    {
        "phq_id": "mock-bn-001",
        "title": "Brunei National Day Celebrations 2027",
        "description": "Brunei's National Day on 23 February is marked with a grand parade in Bandar Seri Begawan featuring military displays, cultural performances, and a royal address at Lapangan Terbang Lama.",
        "category": "observances",
        "labels": ["national-day", "parade", "royal", "brunei"],
        "start_dt": _dt("2027-02-23"),
        "end_dt":   _dt("2027-02-23"),
        "timezone": "Asia/Brunei",
        "coords":   _wkt(114.9420, 4.9031),
        "country": "BN", "country_name": "Brunei",
        "state": "Brunei-Muara", "city": "Bandar Seri Begawan",
        "venue_name": "Lapangan Terbang Lama (Old Airport)",
        "venue_address": "Old Airport, Berakas, Bandar Seri Begawan, Brunei",
        "scope": "country", "rank": 72, "local_rank": 97,
        "phq_attendance": 25000, "predicted_spend": 2000000, "currency": "BND",
        "image_url": _IMGS["parade"],
        "entities": [],
    },

    # ── Timor-Leste ───────────────────────────────────────────────────────────
    {
        "phq_id": "mock-tl-001",
        "title": "Timor-Leste Independence Day Festival 2026",
        "description": "Dili commemorates Timor-Leste's 2002 restoration of independence with a national celebration featuring traditional tais weaving displays, Timorese music, and a presidential address.",
        "category": "observances",
        "labels": ["independence-day", "national", "traditional", "dili"],
        "start_dt": _dt("2026-05-20"),
        "end_dt":   _dt("2026-05-20"),
        "timezone": "Asia/Dili",
        "coords":   _wkt(125.5736, -8.5586),
        "country": "TL", "country_name": "Timor-Leste",
        "state": "Dili", "city": "Dili",
        "venue_name": "Dili Waterfront & Tasi Tolu",
        "venue_address": "Avenida de Portugal, Dili, Timor-Leste",
        "scope": "country", "rank": 68, "local_rank": 95,
        "phq_attendance": 20000, "predicted_spend": 500000, "currency": "USD",
        "image_url": _IMGS["cultural"],
        "entities": [],
    },

    # ── More Indonesia ────────────────────────────────────────────────────────
    {
        "phq_id": "mock-id-006",
        "title": "Toraja Funeral Ceremony (Rambu Solo) Season 2026",
        "description": "The Torajan Ma'nene and Rambu Solo funeral ceremonies in Tana Toraja are among the world's most elaborate burial rites. August–September is peak season when dozens of families hold ceremonies.",
        "category": "festivals",
        "labels": ["toraja", "funeral", "rambu-solo", "cultural", "sulawesi"],
        "start_dt": _dt("2026-08-01"),
        "end_dt":   _dt("2026-09-30"),
        "timezone": "Asia/Makassar",
        "coords":   _wkt(119.8743, -3.0473),
        "country": "ID", "country_name": "Indonesia",
        "state": "South Sulawesi", "city": "Rantepao",
        "venue_name": "Tana Toraja Regency",
        "venue_address": "Rantepao, Tana Toraja, South Sulawesi",
        "scope": "country", "rank": 73, "local_rank": 95,
        "phq_attendance": 30000, "predicted_spend": 1500000, "currency": "IDR",
        "image_url": _IMGS["cultural"],
        "entities": [],
    },
    {
        "phq_id": "mock-id-007",
        "title": "Komodo Dragon Festival Labuan Bajo 2026",
        "description": "An eco-tourism and culture festival at the gateway to Komodo National Park, featuring diving competitions, traditional Manggarai dances, and island boat races in Labuan Bajo.",
        "category": "festivals",
        "labels": ["komodo", "eco-tourism", "diving", "flores"],
        "start_dt": _dt("2026-08-14"),
        "end_dt":   _dt("2026-08-17"),
        "timezone": "Asia/Makassar",
        "coords":   _wkt(119.8854, -8.4966),
        "country": "ID", "country_name": "Indonesia",
        "state": "East Nusa Tenggara", "city": "Labuan Bajo",
        "venue_name": "Labuan Bajo Waterfront",
        "venue_address": "Labuan Bajo, Manggarai Barat, NTT, Indonesia",
        "scope": "country", "rank": 66, "local_rank": 88,
        "phq_attendance": 8000, "predicted_spend": 2000000, "currency": "IDR",
        "image_url": _IMGS["nature"],
        "entities": [],
    },

    # ── More Singapore ────────────────────────────────────────────────────────
    {
        "phq_id": "mock-sg-005",
        "title": "Singapore Tech Summit 2026",
        "description": "Singapore's flagship technology conference draws 20,000 delegates to Marina Bay Sands for keynotes, workshops, and networking on AI, fintech, clean energy, and smart cities.",
        "category": "conferences",
        "labels": ["technology", "ai", "fintech", "smart-city"],
        "start_dt": _dt("2026-11-02"),
        "end_dt":   _dt("2026-11-04"),
        "timezone": "Asia/Singapore",
        "coords":   _wkt(103.8612, 1.2838),
        "country": "SG", "country_name": "Singapore",
        "state": "Bayfront", "city": "Singapore",
        "venue_name": "Marina Bay Sands Expo & Convention Centre",
        "venue_address": "10 Bayfront Avenue, Singapore 018956",
        "scope": "international", "rank": 85, "local_rank": 94,
        "phq_attendance": 20000, "predicted_spend": 25000000, "currency": "SGD",
        "image_url": _IMGS["tech"],
        "entities": [{"name": "Marina Bay Sands", "type": "venue"}],
    },

    # ── More Malaysia ─────────────────────────────────────────────────────────
    {
        "phq_id": "mock-my-005",
        "title": "George Town Festival 2026",
        "description": "An international arts festival held in UNESCO-listed George Town, Penang, featuring live art installations, performing arts, music, and talks across the historic city's streets and heritage buildings.",
        "category": "festivals",
        "labels": ["arts", "george-town", "penang", "heritage", "mural"],
        "start_dt": _dt("2026-08-01"),
        "end_dt":   _dt("2026-08-31"),
        "timezone": "Asia/Kuala_Lumpur",
        "coords":   _wkt(100.3401, 5.4141),
        "country": "MY", "country_name": "Malaysia",
        "state": "Penang", "city": "George Town",
        "venue_name": "George Town Heritage Zone",
        "venue_address": "George Town, Penang, Malaysia",
        "scope": "international", "rank": 76, "local_rank": 93,
        "phq_attendance": 100000, "predicted_spend": 5000000, "currency": "MYR",
        "image_url": _IMGS["art"],
        "entities": [],
    },
    {
        "phq_id": "mock-my-006",
        "title": "Hari Gawai Dayak Festival Sarawak 2026",
        "description": "The Dayak harvest festival (June 1–2) is celebrated across Sarawak's longhouses and in Kuching with tuak (rice wine), traditional Iban dance, blowpipe competitions, and cockfighting.",
        "category": "observances",
        "labels": ["gawai", "dayak", "iban", "harvest", "borneo", "longhouse"],
        "start_dt": _dt("2026-06-01"),
        "end_dt":   _dt("2026-06-02"),
        "timezone": "Asia/Kuching",
        "coords":   _wkt(110.3592, 1.5726),
        "country": "MY", "country_name": "Malaysia",
        "state": "Sarawak", "city": "Kuching",
        "venue_name": "Sarawak Cultural Village & longhouses across Sarawak",
        "venue_address": "Sarawak, Malaysia",
        "scope": "region", "rank": 74, "local_rank": 96,
        "phq_attendance": 400000, "predicted_spend": 7000000, "currency": "MYR",
        "image_url": _IMGS["traditional"],
        "entities": [],
    },

    # ── More Vietnam ──────────────────────────────────────────────────────────
    {
        "phq_id": "mock-vn-004",
        "title": "Da Nang International Fireworks Festival 2026",
        "description": "DIFF brings competing nations to the Han River Bridge for spectacular 25-minute firework displays over two months. The theme-based competitions are judged internationally and attract millions.",
        "category": "festivals",
        "labels": ["fireworks", "da-nang", "han-river", "international", "competition"],
        "start_dt": _dt("2026-06-06"),
        "end_dt":   _dt("2026-07-31"),
        "timezone": "Asia/Ho_Chi_Minh",
        "coords":   _wkt(108.2208, 16.0544),
        "country": "VN", "country_name": "Vietnam",
        "state": "Da Nang", "city": "Da Nang",
        "venue_name": "Han River Bridge Area",
        "venue_address": "Nguyễn Văn Linh, Hải Châu, Da Nang, Vietnam",
        "scope": "international", "rank": 86, "local_rank": 97,
        "phq_attendance": 800000, "predicted_spend": 15000000, "currency": "VND",
        "image_url": _IMGS["fireworks"],
        "entities": [],
    },

    # ── More Thailand ─────────────────────────────────────────────────────────
    {
        "phq_id": "mock-th-005",
        "title": "Asean Night Bazaar Chiang Rai 2026",
        "description": "Chiang Rai's famous night bazaar brings together tribal crafts, northern Thai food, live music, and cultural performances from hill-tribe communities of the Golden Triangle region.",
        "category": "community",
        "labels": ["night-market", "crafts", "hill-tribe", "chiang-rai"],
        "start_dt": _dt("2026-01-01"),
        "end_dt":   _dt("2026-12-31"),
        "timezone": "Asia/Bangkok",
        "coords":   _wkt(99.8341, 19.9105),
        "country": "TH", "country_name": "Thailand",
        "state": "Chiang Rai", "city": "Chiang Rai",
        "venue_name": "Night Bazaar Chiang Rai",
        "venue_address": "Phahonyothin Rd, Chiang Rai 57000",
        "scope": "region", "rank": 57, "local_rank": 85,
        "phq_attendance": 500000, "predicted_spend": 6000000, "currency": "THB",
        "image_url": _IMGS["night_market"],
        "entities": [],
    },

    # ── More Philippines ──────────────────────────────────────────────────────
    {
        "phq_id": "mock-ph-004",
        "title": "Philippine Game Developers Conference 2026",
        "description": "PGDC is Southeast Asia's premier game development conference, gathering game developers, designers, and publishers to discuss trends in mobile, PC, and console gaming in the region.",
        "category": "conferences",
        "labels": ["gaming", "gamedev", "technology", "esports"],
        "start_dt": _dt("2026-05-22"),
        "end_dt":   _dt("2026-05-24"),
        "timezone": "Asia/Manila",
        "coords":   _wkt(121.0244, 14.5535),
        "country": "PH", "country_name": "Philippines",
        "state": "Metro Manila", "city": "Pasay",
        "venue_name": "SMX Convention Center",
        "venue_address": "Mall of Asia, Pasay, Metro Manila, Philippines",
        "scope": "international", "rank": 68, "local_rank": 87,
        "phq_attendance": 8000, "predicted_spend": 3000000, "currency": "PHP",
        "image_url": _IMGS["gaming"],
        "entities": [],
    },

    # ── Indonesia (more) ──────────────────────────────────────────────────────
    {
        "phq_id": "mock-id-008",
        "title": "Jakarta Fashion Week 2026",
        "description": "JFW is the largest fashion event in Southeast Asia, showcasing Indonesian and regional designers at Senayan City. Over 100 designers present collections across six days of runway shows.",
        "category": "expos",
        "labels": ["fashion", "design", "style", "jakarta"],
        "start_dt": _dt("2026-10-26"),
        "end_dt":   _dt("2026-11-01"),
        "timezone": "Asia/Jakarta",
        "coords":   _wkt(106.7996, -6.2263),
        "country": "ID", "country_name": "Indonesia",
        "state": "DKI Jakarta", "city": "Jakarta",
        "venue_name": "Senayan City",
        "venue_address": "Jl. Asia Afrika No. 8, Senayan, Jakarta 10270",
        "scope": "international", "rank": 77, "local_rank": 91,
        "phq_attendance": 50000, "predicted_spend": 8000000, "currency": "IDR",
        "image_url": _IMGS["fashion"],
        "entities": [],
    },

    # ── AFF Championship (cross-country football) ──────────────────────────────
    {
        "phq_id": "mock-aff-001",
        "title": "AFF Mitsubishi Electric Cup 2026 Final",
        "description": "The ASEAN Football Federation Championship Final between the two top-ranked ASEAN nations. The premier football event in Southeast Asia, watched by millions across the region.",
        "category": "sports",
        "labels": ["football", "soccer", "aff", "asean", "championship"],
        "start_dt": _dt("2026-12-26"),
        "end_dt":   _dt("2026-12-26"),
        "timezone": "Asia/Jakarta",
        "coords":   _wkt(106.8018, -6.2183),
        "country": "ID", "country_name": "Indonesia",
        "state": "DKI Jakarta", "city": "Jakarta",
        "venue_name": "Gelora Bung Karno Stadium",
        "venue_address": "Pintu I GBK, Gelora, Tanah Abang, Jakarta 10270",
        "scope": "international", "rank": 90, "local_rank": 98,
        "phq_attendance": 78000, "predicted_spend": 5000000, "currency": "IDR",
        "image_url": _IMGS["football"],
        "entities": [{"name": "Gelora Bung Karno", "type": "venue"}],
    },
]


# ─── CLI ───────────────────────────────────────────────────────────────────────

@click.command()
@click.option("--dry-run", is_flag=True, help="Preview rows without writing to Supabase.")
@click.option("--clear",   is_flag=True, help="Delete all mock-* rows first, then re-seed.")
def main(dry_run: bool, clear: bool) -> None:
    """Seed the Supabase events table with mock ASEAN event data."""

    logger.info("Mock ASEAN event seeder — %d events to insert", len(MOCK_EVENTS))

    client = get_client()

    if clear and not dry_run:
        logger.info("Deleting existing mock rows …")
        resp = client.table("events").delete().like("phq_id", "mock-%").execute()
        logger.info("Deleted mock rows.")

    if dry_run:
        click.echo(f"\n[DRY-RUN] Would upsert {len(MOCK_EVENTS)} events:\n")
        for e in MOCK_EVENTS:
            click.echo(
                f"  {e['phq_id']:<20}  [{e['country']}]  {e['category']:<16}  {e['title'][:60]}"
            )
        click.echo(f"\n  Total: {len(MOCK_EVENTS)} events — nothing written.\n")
        return

    logger.info("Upserting %d mock events …", len(MOCK_EVENTS))
    client.table("events").upsert(MOCK_EVENTS, on_conflict="phq_id").execute()
    logger.info("Done — %d events seeded successfully.", len(MOCK_EVENTS))

    click.echo(f"\n✓ Seeded {len(MOCK_EVENTS)} ASEAN mock events into Supabase.\n")


if __name__ == "__main__":
    main()
